config/routes.rb
Rails.application.routes.draw do

  root :to => "movies#index"

  get "upvote" => "movies#upvote", :as => "upvote"
  get "downvote" => "movies#downvote", :as => "downvote"
  get "retract" => "movies#retract", :as => "retract"
  get "changevote" => "movies#changevote", :as => "changevote"

  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  get "logout" => "sessions#destroy", :as => "logout"

  resources :users, only: [:show, :new, :create]
  resources :sessions, only: [:create, :destroy]
  resources :movies, only: [:index, :show, :new, :create]

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  belongs_to :user
  has_many :votes

  validates :title, :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :movies, dependent: :destroy
  has_many :votes, through: :movies

  has_secure_password

  validates :email, :username, presence: true
  validates :email, :username, uniqueness: true
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message: 'Doesn’t look valid.'
  validates :username, length: { minimum: 2 }
  validates :password, length: { in: 6..20 }
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie

  enum category: { down: 0, up: 1 }

  validates_uniqueness_of :movie_id, scope: :user_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :require_login

  private

  # Minimal sessions and authorization implementations.
  def current_user
    current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def require_login
    unless current_user
      redirect_to login_path, notice: 'Log in to get access!'
    end
  end

  # Set default sorting column and direction.
  def sort_column
    Movie.column_names.include?(params[:sort]) ? params[:sort] : 'title'
  end
  helper_method :sort_column

  def sort_direction
    %w(asc desc).include?(params[:direction]) ? params[:direction] : 'asc'
  end
  helper_method :sort_direction
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  skip_before_filter :require_login, :only => [:index, :show]

  def index
    @movies = Movie.order(sort_column + ' ' + sort_direction)
    @posters = @movies.map { |m| User.find(m.user_id) }
  end

  def show
    @movie = Movie.find(params[:id])
    @poster = User.find_by_id(@movie.user_id).username
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = current_user.movies.build(movie_params)
    @movie.user_id = current_user.id
    @movie.save

    redirect_to @movie
  end

  def upvote
    @movie = Movie.find(params[:movie_id])
    @movie.increment!(:upvotes)
    vote = @movie.votes.find_or_create_by(
      user_id: current_user.id,
      movie_id: params[:movie_id])
    vote.up!
    vote.save

    redirect_to movies_path
  end

  def downvote
    @movie = Movie.find(params[:movie_id])
    @movie.increment!(:downvotes)
    vote = @movie.votes.find_or_create_by(
      user_id: current_user.id,
      movie_id: params[:movie_id])
    vote.down!
    vote.save

    redirect_to movies_path
  end

  def changevote
    @movie = Movie.find(params[:movie_id])
    vote = Vote.find_by_movie_id_and_user_id(params[:movie_id], current_user.id)
    @movie.decrement!(vote.category + 'votes')
    Vote.destroy(vote.id)

    if params[:category] == 'up'
      upvote
    else # Down
      downvote
    end
  end

  def retract
    @movie = Movie.find(params[:movie_id])
    vote = Vote.find_by_movie_id_and_user_id(params[:movie_id], current_user.id)
    @movie.decrement!(vote.category + 'votes')
    Vote.destroy(vote.id)

    redirect_to movies_path
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :description, :upvotes, :downvotes)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_filter :require_login

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Logged in!'
    else
      flash.now.alert = 'Email or password is invalid.'
      render 'new'
    end
  end

  def destroy
    reset_session
    redirect_to root_url, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_filter :require_login, only: [:new, :create]

  def show
    @username = User.find(params[:id]).username.titleize
    @movies = Movie.where(user_id: params[:id]).order(
      sort_column + ' ' + sort_direction)
  end

  def new
    @user = User.new
  end

  # Sign up and auto-login
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'Thanks for signing up!'
    else
      flash[:error] = 'Something went wrong. Try again!'
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :user_id,
      :username,
      :email,
      :password,
      :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Setup sorting links and alternate between ASC and DESC.
  def sortable(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == 'asc' ? 'desc' : 'asc'
    link_to title, { sort: column, direction: direction },
    { class: 'btn btn-default active', role: 'button' }
  end

  def time_passed(since)
    time_ago_in_words since
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
  def poster(movie)
    User.find_by_id(movie.user_id).username
  end

  def upvoted?(movie_id)
    !Vote.find_by_movie_id_and_user_id_and_category(movie_id, current_user.id, 1).nil?
  end

  def downvoted?(movie_id)
    !Vote.find_by_movie_id_and_user_id_and_category(movie_id, current_user.id, 0).nil?
  end
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Movierama", root_url, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to current_user.username, user_path(current_user.id) %></li>
          <li><%= link_to "Log Out", logout_path %>
        <% else %>
          <li><%= link_to "Sign Up", signup_path %></li>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <title>Movierama</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/navbar" %>
  <div class="container">
    <% flash.each do |name, msg| %>
      <div class="alert alert-warning" role="alert"><%= msg %></div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/movies/_sort.html.erb
<div class='sort-row row col-xs-8'>
  Sort by:
  <div class='btn-group' role='group'>
    <%= sortable 'title' %></button>
    <%= sortable 'created_on', 'Date' %></button>
    <%= sortable 'upvotes' %></button>
    <%= sortable 'downvotes' %></button>
  </div>
</div>

app/views/movies/index.html.erb
<h1>All Movies</h1>

<%= render 'movies/sort' %>

<%= link_to 'New Movie', new_movie_path,
  { class: 'btn btn-primary', role: 'button' } %>

<br><br>
<ul class='media-list col-xs-8'>
<% @movies.zip(@posters).each do |movie, poster| %>
  <li class='media'>
    <div class='media-body'>

      <h4 class='media-heading'><%= movie.title %></h4>
      <h5>Posted by <%= link_to poster.username, user_path(poster.id) %>,
      <%= time_passed(movie.created_on) %> ago</h5>
      <%= movie.description %>
      <br><br>

      upvotes: <span class='badge bdg-upvote'><%= movie.upvotes %></span> |
      downvotes: <span class='badge bdg-downvote'><%= movie.downvotes %></span>
      <br>

      <% unless session[:user_id].nil? %>
        <% if movie.user_id == current_user.id %>
          Bummer! Can’t vote on movies you ’ve submitted.
        <% else %>
          <% if upvoted? movie.id %>
            You ’ve upvoted this movie! Maybe
            <%= link_to :downvote,
              changevote_path(movie_id: movie.id, category: :down) %>
              or <%= link_to :retract, retract_path(movie_id: movie.id) %> instead?
          <% elsif downvoted? movie.id %>
            You ’ve downvoted this movie! Maybe
            <%= link_to :upvote,
              changevote_path(movie_id: movie.id, category: :up) %>
              or <%= link_to :retract, retract_path(movie_id: movie.id) %> instead?
          <% else %>
            <%= link_to :upvote, upvote_path(movie_id: movie.id) %> or
            <%= link_to :downvote, downvote_path(movie_id: movie.id) %>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <br>
  </li>
<% end %>
</ul>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= form_for @movie, :html => { :class => 'form col-xs-8' } do |f| %>
  <% if @movie.errors.any? %>
    <div class="error_messages">
    <% for message in @movie.errors.full_messages %>
      <div class="alert alert-danger" role="alert"><strong>Oh snap! </strong><%= message %></div>
    <% end %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control", placeholder: "Enter movie title" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control", placeholder: "Enter movie description" %>
  </div>

  <div class="form-group">
    <button type="submit" class="btn btn-default">Create Movie</button>
  </div>
<% end %>

app/views/movies/show.html.erb
<h1>Show Movie</h1>

<%= form_for @movie, :html => { :class => 'form col-xs-8' } do |f| %>
  <% if @movie.errors.any? %>
    <div class="error_messages">
    <% for message in @movie.errors.full_messages %>
      <div class="alert alert-danger" role="alert"><strong>Oh snap! </strong><%= message %></div>
    <% end %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= @movie.title %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= @movie.description %>
  </div>
  <div class="form-group">
    <%= f.label :posted_by %>
    <%= @poster %>
  </div>
  <div class="form-group">
    <%= f.label :publication_date %>
    <%= @movie.created_on %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user, :html => { :class => 'form col-xs-8' } do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
    <% for message in @user.errors.full_messages %>
        <div class="alert alert-danger alert-dismissible fade in" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <strong>Oh snap! </strong><%= message %>
        </div>
    <% end %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control", placeholder: "Enter your e-mail" %>
  </div>
  <div class="form-group">
    <%= f.label :username %>
    <%= f.text_field :username, class: "form-control", placeholder: "Enter your username" %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control", placeholder: "Enter your password" %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm your password" %>
  </div>

  <div class="form-group">
    <button type="submit" class="btn btn-primary">Sign in</button>
  </div>
<% end %>

app/views/users/show.html.erb
<h1><%= @username %>'s Movies</h1>

<%= render "movies/sort" %>

<ul class="media-list col-xs-8">
  <% @movies.each do |movie| %>
    <li class="media">
      <div class="media-body">
        <h4 class="media-heading"><%= movie.title %></h4>
        <h5>Posted by <%= link_to poster(movie), user_path(:id => movie.user_id) %>,
        <%= time_passed(movie.created_on) %> ago</h5>
        <%= movie.description %>
        <br><br>
        upvotes: <span class="badge bdg-upvote"><%= movie.upvotes %></span> |
        downvotes: <span class="badge bdg-downvote"><%= movie.downvotes %></span>
        <br>
        <% unless session[:user_id].nil? %>
          <% if movie.user_id == current_user.id %>
            Bummer! Can’t vote on movies you ’ve submitted.
          <% else %>
            <% if upvoted? movie.id %>
              You ’ve upvoted this movie! Maybe
              <%= link_to :downvote,
                changevote_path(:movie_id => movie.id, :category => :down) %>
                or <%= link_to :retract, retract_path(:movie_id => movie.id) %> instead?
            <% elsif downvoted? movie.id %>
              You ’ve downvoted this movie! Maybe
              <%= link_to :upvote,
                changevote_path(:movie_id => movie.id, :category => :up) %>
                or <%= link_to :retract, retract_path(:movie_id => movie.id) %> instead?
            <% else %>
              <%= link_to :upvote, upvote_path(:movie_id => movie.id) %> or
              <%= link_to :downvote, downvote_path(:movie_id => movie.id) %>
            <% end %>
          <% end %>
        <% end %>

      </div>
      <br>
    </li>
  <% end %>
</ul>